name: Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ # Add additional dependencies if required

    # Compile the project
    - name: Compile project
      run: |
        g++ -Wall -std=c++17 -o bin/test main.cpp api.cpp

    # Run unit tests
    - name: Run unit tests
      run: |
        ./bin/test # Replace this with the actual command to execute your tests
