name: Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: [self-hosted, Team-6-PQ]

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Compile the project
    - name: Compile project
      run: |
        g++ -std=c++17 -o test main.cpp api.cpp

    # Run unit tests
    - name: Run unit tests
      run: |
        ./test # Replace this with the actual command to execute your tests
